#!/usr/bin/php -q

<?php

$file_path = $argv[1];

if(!file_exists($file_path)) {

  echo $file_path;
  echo "File does not exist.";

} else {

  $file = fopen($file_path, "r") or exit("Unable to open file!");
  //Output a line of the file until the end is reached
  while(!feof($file)) {
    $line = fgets($file);

    echo "Checking: " . $line;

    $url = $line;

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL,$url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $html = curl_exec($ch);

    $status_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $redirect_url = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);

    if($status_code == "301" || $status_code == "200") {
      echo "\033[32m" . $status_code . ": " . $redirect_url . "\n" . "\033[37m\r\n";
    } else {
      echo "\033[31m" . $status_code . ": " . $redirect_url . "\n" . "\033[37m\r\n";
    }

    sleep(1);

  }
  fclose($file);

}

?>